
services:
  drupal:
    image: drupal:9
    ports:
      - 8080:80

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - psql-data:/var/lib/postgresql/data

volumes:
  psql-data: